#!/usr/bin/env bash

source ../envs/paths.env
source ../envs/secrets.env

rm -rf builds
mkdir builds

echo
echo "Starting Unity build..."

# -logFile - \
# -stackTraceLogType Full 
# -verbose 

"$UNITY_PATH" \
  -batchmode -quit \
  -projectPath "$PROJECT_PATH_ANDROID" \
  -executeMethod AndroidBuildCommand.BuildAndroidApp \
  buildPath="$(pwd)/builds/app.apk" \
  KeystoreName="$KeystoreName" \
  KeystorePass="$KeystorePass" \
  KeyaliasName="$KeyaliasName" \
  KeyaliasPass="$KeyaliasPass" \

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "Unity build failed with exit code $EXIT_CODE."
  exit 1
else
  echo "Unity build completed."
  exit 0
fi
