#!/usr/bin/env bash

source ../envs/paths.env

rm -rf builds
mkdir builds

echo
echo "Starting Unity build..."

"$UNITY_PATH" \
  -batchmode -quit \
  -projectPath "$PROJECT_PATH_MACOS" \
  -executeMethod MacOSServerBuildCommand.BuildMacServer \
  buildPath="$(pwd)/builds/server_app" \

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "Unity build failed with exit code $EXIT_CODE."
  exit 1
else
  echo "Unity build completed."
  exit 0
fi
